import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Pacifico,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";
import { AppWrapper, Navbar } from "@/components";
import { ThemeProvider } from "@/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} ${pacifico.variable} antialiased`}
      >
        <ThemeProvider>
          <AppWrapper>
            <Navbar />
            {children}
          </AppWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
